# Explicit target providers, all found within the private target sysroot.
find_package(absl CONFIG REQUIRED)
find_package(re2 CONFIG REQUIRED)
find_package(Protobuf CONFIG REQUIRED)
find_package(utf8_range CONFIG REQUIRED)
find_package(date CONFIG REQUIRED)
find_package(boost_mp11 CONFIG REQUIRED)
find_package(nlohmann_json CONFIG REQUIRED)
find_package(Microsoft.GSL CONFIG REQUIRED)
find_package(FlatBuffers CONFIG REQUIRED)
find_package(ONNX CONFIG REQUIRED)
find_package(Eigen3 CONFIG REQUIRED)
get_filename_component(_tdvp_ort_source_root "${CMAKE_SOURCE_DIR}/.." ABSOLUTE)
set_source_files_properties("${_tdvp_ort_source_root}/onnxruntime/core/session/environment.cc"
  PROPERTIES COMPILE_DEFINITIONS TDVP_ONNX_PUBLIC_AUTO_SCHEMA_REGISTRY=1)
unset(_tdvp_ort_source_root)
if(NOT TARGET flatbuffers::flatbuffers AND TARGET flatbuffers::flatbuffers_shared)
  add_library(flatbuffers::flatbuffers ALIAS flatbuffers::flatbuffers_shared)
endif()
if(NOT TARGET flatbuffers::flatc)
  if(NOT EXISTS "${TDVP_NATIVE_FLATC}")
    message(FATAL_ERROR "Source-locked native flatc is required")
  endif()
  add_executable(flatbuffers::flatc IMPORTED GLOBAL)
  set_target_properties(flatbuffers::flatc PROPERTIES IMPORTED_LOCATION "${TDVP_NATIVE_FLATC}")
endif()
