#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
for package in make pkgconf patch diffutils strace; do
  env_file="$repo_root/packages/$package/package.env"
  grep -Fqx "PACKAGE='$package'" "$env_file"
  grep -Fqx "PACKAGE_RELEASES='r9 r10'" "$env_file"
  grep -Fq 'tdvp_buildroot_command_package' "$repo_root/packages/$package/build.sh"
  test -f "$repo_root/packages/$package/source.lock"
done
for package in tree less file which jq dos2unix grep sed findutils gawk htop nano; do
  env_file="$repo_root/packages/$package/package.env"
  grep -Fqx "PACKAGE='$package'" "$env_file"
  grep -Fqx "PACKAGE_RELEASES='r10'" "$env_file"
  grep -Fq 'tdvp_buildroot_command_package' "$repo_root/packages/$package/build.sh"
  test -f "$repo_root/packages/$package/source.lock"
done
grep -Fq '/usr/libexec/tdvp-' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'runtime data path must be an absolute clean file path' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'tdvp_remove_elf_runtime_search_paths' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'chmod 0755 -- "$payload_dir"' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'tdvp_assert_elf_without_runtime_search_path' "$repo_root/scripts/build-ipk.sh"
grep -Fqx 'packages/*/root' "$repo_root/.gitignore"
grep -Fq 'BR2_PACKAGE_BUSYBOX_SHOW_OTHERS' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'tdvp_is_selected_command' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'TDVP_COMMAND_FRONTEND_NAMES' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'base-overlay audit remains the authority' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'readlink -- "$source"' "$repo_root/support/buildroot-command-package.sh"
grep -Fq "'pkgconf pkg-config'" "$repo_root/packages/pkgconf/build.sh"
grep -Fq "TDVP_COMMAND_BUILDROOT_MAKE_VARIABLES='PKGCONF_CONF_OPTS=--disable-shared --enable-static'" "$repo_root/packages/pkgconf/build.sh"
grep -Fq "'diff cmp diff3 sdiff'" "$repo_root/packages/diffutils/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='diff=tdvp-diff cmp=tdvp-cmp'" "$repo_root/packages/diffutils/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='patch=tdvp-patch'" "$repo_root/packages/patch/build.sh"
grep -Fq "'tree'" "$repo_root/packages/tree/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='tree=tdvp-tree'" "$repo_root/packages/tree/build.sh"
grep -Fq "'less'" "$repo_root/packages/less/build.sh"
grep -Fqx "PACKAGE_DEPENDS='libncursesw (= 6.4-20230603-1)'" "$repo_root/packages/less/package.env"
grep -Fqx "PACKAGE_BUILD_DEPENDS='libncursesw'" "$repo_root/packages/less/package.env"
grep -Fq "'file'" "$repo_root/packages/file/build.sh"
grep -Fq "'/usr/share/misc/magic.mgc'" "$repo_root/packages/file/build.sh"
grep -Fqx "PACKAGE_DEPENDS='libmagic (= 5.45-1)'" "$repo_root/packages/file/package.env"
grep -Fqx "PACKAGE_BUILD_DEPENDS='libmagic'" "$repo_root/packages/file/package.env"
grep -Fqx "PACKAGE='libmagic'" "$repo_root/packages/libmagic/package.env"
grep -Fqx "PACKAGE_KIND='shared-library'" "$repo_root/packages/libmagic/package.env"
grep -Fqx "PACKAGE_DEPENDS='libz (= 1.3.1-1)'" "$repo_root/packages/libmagic/package.env"
grep -Fq 'tdvp_build_archive_library' "$repo_root/packages/libmagic/build.sh"
test -f "$repo_root/packages/libmagic/source.lock"
grep -Fqx "PACKAGE='libz'" "$repo_root/packages/libz/package.env"
grep -Fqx "PACKAGE_KIND='shared-library'" "$repo_root/packages/libz/package.env"
grep -Fq 'tdvp_build_archive_library' "$repo_root/packages/libz/build.sh"
test -f "$repo_root/packages/libz/source.lock"
grep -Fq "'which'" "$repo_root/packages/which/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='which=tdvp-which'" "$repo_root/packages/which/build.sh"
grep -Fq "'jq'" "$repo_root/packages/jq/build.sh"
grep -Fqx "PACKAGE_DEPENDS='libjq (= 1.7.1-1)'" "$repo_root/packages/jq/package.env"
grep -Fqx "PACKAGE='libjq'" "$repo_root/packages/libjq/package.env"
grep -Fqx "PACKAGE_KIND='shared-library'" "$repo_root/packages/libjq/package.env"
grep -Fq 'tdvp_build_archive_library' "$repo_root/packages/libjq/build.sh"
test -f "$repo_root/packages/libjq/source.lock"
grep -Fqx "PACKAGE_DEPENDS='libpcre2-8 (= 10.44-1)'" "$repo_root/packages/grep/package.env"
grep -Fqx "PACKAGE_BUILD_DEPENDS='libpcre2-8'" "$repo_root/packages/grep/package.env"
grep -Fqx "PACKAGE='libpcre2-8'" "$repo_root/packages/libpcre2-8/package.env"
grep -Fqx "PACKAGE_KIND='shared-library'" "$repo_root/packages/libpcre2-8/package.env"
grep -Fq 'tdvp_build_archive_library' "$repo_root/packages/libpcre2-8/build.sh"
test -f "$repo_root/packages/libpcre2-8/source.lock"
grep -Fqx "PACKAGE='libncursesw'" "$repo_root/packages/libncursesw/package.env"
grep -Fqx "PACKAGE_KIND='shared-library'" "$repo_root/packages/libncursesw/package.env"
grep -Fq 'tdvp_build_archive_library' "$repo_root/packages/libncursesw/build.sh"
test -f "$repo_root/packages/libncursesw/source.lock"
grep -Fqx "PACKAGE='libreadline'" "$repo_root/packages/libreadline/package.env"
grep -Fqx "PACKAGE_DEPENDS='libncursesw (= 6.4-20230603-1)'" "$repo_root/packages/libreadline/package.env"
grep -Fqx "PACKAGE_BUILD_DEPENDS='libncursesw'" "$repo_root/packages/libreadline/package.env"
grep -Fq 'tdvp_build_archive_library' "$repo_root/packages/libreadline/build.sh"
test -f "$repo_root/packages/libreadline/source.lock"
grep -Fqx "PACKAGE_DEPENDS='libreadline (= 8.2-1)'" "$repo_root/packages/gawk/package.env"
grep -Fqx "PACKAGE_BUILD_DEPENDS='libreadline'" "$repo_root/packages/gawk/package.env"
grep -Fq "'dos2unix'" "$repo_root/packages/dos2unix/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='dos2unix=tdvp-dos2unix'" "$repo_root/packages/dos2unix/build.sh"
grep -Fq "'grep'" "$repo_root/packages/grep/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='grep=tdvp-grep'" "$repo_root/packages/grep/build.sh"
! grep -Fq 'egrep fgrep' "$repo_root/packages/grep/build.sh"
grep -Fq "'sed'" "$repo_root/packages/sed/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='sed=tdvp-sed'" "$repo_root/packages/sed/build.sh"
grep -Fq "'find xargs'" "$repo_root/packages/findutils/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='find=tdvp-find xargs=tdvp-xargs'" "$repo_root/packages/findutils/build.sh"
grep -Fq "'gawk awk'" "$repo_root/packages/gawk/build.sh"
grep -Fq "TDVP_COMMAND_FRONTEND_NAMES='awk=tdvp-awk'" "$repo_root/packages/gawk/build.sh"
grep -Fqx "VERSION='5.3.1-2'" "$repo_root/packages/gawk/package.env"
grep -Fq "'htop'" "$repo_root/packages/htop/build.sh"
grep -Fqx "PACKAGE_DEPENDS='libncursesw (= 6.4-20230603-1)'" "$repo_root/packages/htop/package.env"
grep -Fq "TDVP_COMMAND_BUILDROOT_DISABLE_SYMBOLS='BR2_PACKAGE_LIBCAP'" "$repo_root/packages/htop/build.sh"
grep -Fq 'TDVP_COMMAND_BUILDROOT_DISABLE_SYMBOLS' "$repo_root/support/buildroot-command-package.sh"
grep -Fq 'TDVP_COMMAND_BUILDROOT_MAKE_VARIABLES' "$repo_root/support/buildroot-command-package.sh"
grep -Fq "'nano'" "$repo_root/packages/nano/build.sh"
grep -Fqx "PACKAGE_DEPENDS='libncursesw (= 6.4-20230603-1)'" "$repo_root/packages/nano/package.env"
