#!/usr/bin/env bash
set -Eeuo pipefail
IFS=$'\n\t'
repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
env_file="$repo_root/packages/gh/package.env"
build_file="$repo_root/packages/gh/build.sh"
source_lock="$repo_root/packages/gh/source.lock"
module_lock="$repo_root/packages/gh/go-modules.lock"
grep -Fqx "PACKAGE='gh'" "$env_file"
grep -Fqx "PACKAGE_RELEASES='r9 r10 r11'" "$env_file"
grep -Fqx "PACKAGE_AUTO_RUNTIME_DEPENDS=0" "$env_file"
grep -Fq "PACKAGE_DEPENDS='git (= 2.48.1-1), ca-certificates (= 2025.02.1-1)'" "$env_file"
test -f "$source_lock"
test -f "$module_lock"
bash "$repo_root/scripts/verify-source-lock.sh" --package-dir "$repo_root/packages/gh"
grep -Fqx "UPSTREAM_VERSION='2.98.0'" "$source_lock"
grep -Fqx "GO_TOOLCHAIN_VERSION='1.26.7'" "$module_lock"
grep -Fqx "GO_RESOLVED_SUM_SHA256='86ab1fe26ef974a5ebd5745f3f0b48cf32b42cfbaad173569113254e8aab67d8'" "$module_lock"
grep -Fqx "GO_MODULE_VENDOR_ARCHIVE_SHA256='1f9e4f6a0b03aef012a3b7f39a3f35ef05732201d176f4e0c08fc0f82afb91dc'" "$module_lock"
grep -Fq 'tdvp_prepare_locked_go_host_toolchain' "$build_file"
grep -Fq 'tdvp_prepare_go_module_vendor_cache' "$build_file"
grep -Fq 'tdvp_extract_go_module_vendor_cache' "$build_file"
grep -Fq 'GOPROXY=off' "$build_file"
grep -Fq "GOFLAGS='-mod=vendor'" "$build_file"
grep -Fq 'GOOS=linux' "$build_file"
grep -Fq 'GOARCH=riscv64' "$build_file"
grep -Fq 'CGO_ENABLED=0' "$build_file"
grep -Fq 'tdvp_prepare_generated_payload_root' "$build_file"
helper="$repo_root/support/go-module-vendor-cache.sh"
bash -n "$repo_root/scripts/prepare-go-module-vendor-cache.sh"
bash -n "$helper" "$build_file"
grep -Fq 'SOURCE_BUILD_INPUT_1_FILE' "$source_lock"
grep -Fq 'GOPROXY=off' "$build_file"
grep -Fq 'GOSUMDB=off' "$build_file"
grep -Fq 'GONOSUMDB=' "$build_file"
grep -Fq 'tdvp_assert_elf_without_runtime_search_path' "$build_file"
grep -Fq 'Shared library:' "$build_file"
grep -Fq 'mod download all' "$helper"
grep -Fq 'mod verify' "$helper"
grep -Fq 'mod vendor' "$helper"
grep -Fq 'TDVP_GO_MODULE_VENDOR_RETRY_ATTEMPTS' "$helper"
grep -Fq 'Go module vendor resolution attempt' "$helper"
grep -Fq 'retrying with fresh caches' "$helper"
grep -Fq 'cp -- "$source_sum_file" "$source_root/go.sum"' "$helper"
archive_builder="$repo_root/support/go-module-vendor-archive.go"
test -f "$archive_builder"
grep -Fq 'go-module-vendor-archive.go' "$helper"
grep -Fq 'GOTOOLCHAIN=local "$go_binary" run "$archive_builder"' "$helper"
grep -Fq 'compress/gzip' "$archive_builder"
grep -Fq 'tar.FormatPAX' "$archive_builder"
grep -Fq 'gzipWriter.Header.ModTime = epoch' "$archive_builder"
grep -Fq 'tdvp_prepare_go_module_vendor_cache' "$repo_root/scripts/prepare-go-module-vendor-cache.sh"
grep -Fq 'TDVP_SOURCE_CACHE_OFFLINE' "$repo_root/scripts/prepare-go-module-vendor-cache.sh"
if grep -Eq '(curl |releases/download|\.deb|\.rpm|go mod download)' "$build_file"; then
  echo 'gh recipe must not download a prebuilt package' >&2
  exit 1
fi
bash "$repo_root/tests/go-module-vendor-cache-retry.sh"
bash "$repo_root/tests/go-module-vendor-archive.sh"
