get_filename_component(_tdvp_ml_prefix "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
find_package(Eigen3 3.4.90 CONFIG REQUIRED)
if(NOT TARGET ml_dtypes)
  add_library(ml_dtypes INTERFACE IMPORTED GLOBAL)
  set_target_properties(ml_dtypes PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${_tdvp_ml_prefix}/include/ml_dtypes;${_tdvp_ml_prefix}/include/ml_dtypes/include")
  set_target_properties(ml_dtypes PROPERTIES INTERFACE_LINK_LIBRARIES Eigen3::Eigen)
endif()
set(ml_dtypes_FOUND TRUE)
unset(_tdvp_ml_prefix)
