#!/usr/bin/env bash
# Run the same pre-compilation gates in portable CI and every source batch.
set -Eeuo pipefail
repo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
python3 "$repo_root/tests/common-seven-library-policy.py"
python3 "$repo_root/tests/common-system-network-library-policy.py"
python3 "$repo_root/tests/common-event-data-network-policy.py"
python3 "$repo_root/tests/cjson-source-security-policy.py"
python3 "$repo_root/tests/source-copyright-notice-extraction.py"
python3 "$repo_root/tests/source-archive-root-layout.py"
python3 "$repo_root/tests/common-embedded-library-policy.py"
python3 "$repo_root/tests/bsd-library-policy.py"
python3 "$repo_root/tests/mmdb-library-policy.py"
python3 "$repo_root/tests/kerberos-rpc-library-policy.py"
python3 "$repo_root/tests/talloc-tevent-library-policy.py"
python3 "$repo_root/tests/nsl-library-policy.py"
python3 "$repo_root/tests/gdbm-library-policy.py"
python3 "$repo_root/tests/tdb-library-policy.py"
python3 "$repo_root/tests/keyutils-library-policy.py"
python3 "$repo_root/tests/selinux-library-policy.py"
python3 "$repo_root/tests/selinux-notice-projection.py"
python3 "$repo_root/tests/pci-library-policy.py"
python3 "$repo_root/tests/numa-library-policy.py"
python3 "$repo_root/tests/openjpeg-library-policy.py"
python3 "$repo_root/tests/hdf5-aec-library-policy.py"
python3 "$repo_root/tests/gif-library-policy.py"
python3 "$repo_root/tests/imath-library-policy.py"
python3 "$repo_root/tests/openjph-library-policy.py"
python3 "$repo_root/tests/openexr-library-policy.py"
python3 "$repo_root/tests/feed-notice-inventory.py"
python3 "$repo_root/tests/sasl-library-policy.py"
python3 "$repo_root/tests/ldap-library-policy.py"
python3 "$repo_root/tests/aom-library-policy.py"
python3 "$repo_root/tests/avif-yuv-library-policy.py"
python3 "$repo_root/tests/heif-hevc-library-policy.py"
python3 "$repo_root/tests/dav1d-library-policy.py"
python3 "$repo_root/tests/gperftools-library-policy.py"
python3 "$repo_root/tests/jxl-color-library-policy.py"
python3 "$repo_root/tests/boost-library-policy.py"
python3 "$repo_root/tests/pkgconfig-build-prefix-normalization.py"
python3 "$repo_root/tests/extra-runtime-owner-version-policy.py"
python3 "$repo_root/tests/node-provider-version-policy.py"
python3 "$repo_root/tests/source-recipe-exact-dependencies.py"
python3 "$repo_root/tests/icu-native-source-layout.py"
python3 "$repo_root/tests/archive-source-license.py"
bash "$repo_root/tests/dev-tools-package-policy.sh"
bash "$repo_root/tests/published-sdk-lzip-policy.sh"
python3 "$repo_root/tests/command-staging-export-integration.py"
python3 "$repo_root/tests/go-package-notices.py"
bash "$repo_root/tests/common-tool-notice-policy.sh"
python3 "$repo_root/tests/notice-projection-lifetime.py"
bash "$repo_root/tests/vim-plugin-notice-policy.sh"
for script in "$repo_root"/scripts/*.sh "$repo_root"/tests/*.sh "$repo_root"/packages/*/build.sh; do
  bash -n "$script"
done
for policy in build-all-source-lock-policy audacious-foundation-policy audacious-package-policy archive-package-policy target-runtime-provider-deferral-policy feed-overlay-composition-policy source-lock-policy; do
  printf 'Batch preflight: %s\n' "$policy"
  bash "$repo_root/tests/$policy.sh"
done
bash "$repo_root/scripts/verify-source-lock.sh" --repo-root "$repo_root" --all
python3 "$repo_root/tests/libssh-library-policy.py"
python3 "$repo_root/tests/berkeleydb-library-policy.py"
echo 'Shared batch preflight: PASS'
