#!/usr/bin/env bash
# Materialise the small development-header overlay required to build feed
# packages against a stripped Buildroot SDK output.  The overlay deliberately
# symlinks the matching sysroot libraries and copies only headers generated by
# the packages already used for the firmware image; it is a build input, never
# a firmware or feed payload.
set -Eeuo pipefail
IFS=$'\n\t'

if [[ $# -ne 4 || "$1" != '--buildroot-output' || "$3" != '--destination' ]]; then
  echo "usage: $0 --buildroot-output <matching-output-directory> --destination <new-overlay-directory>" >&2
  exit 64
fi

output_root=$(cd -- "$2" && pwd)
destination=$4
[[ -d "$output_root/host" && -d "$output_root/build" && -d "$output_root/target" ]] || {
  echo "not a Buildroot output directory: $output_root" >&2
  exit 65
}
[[ ! -e "$destination" ]] || {
  echo "refusing to overwrite existing SDK overlay: $destination" >&2
  exit 66
}

host_dir="$output_root/host"
sysroot=$(find "$host_dir" -type d -path '*/sysroot' -print -quit)
[[ -n "$sysroot" && -d "$sysroot/usr/lib" ]] || {
  echo "matching target sysroot is missing below: $host_dir" >&2
  exit 67
}

copy_tree() {
  local source=$1
  local target=$2
  [[ -d "$source" ]] || {
    echo "required firmware build header directory is missing: $source" >&2
    exit 68
  }
  mkdir -p -- "$(dirname -- "$target")"
  cp -a -- "$source" "$target"
}

copy_file() {
  local source=$1
  local target=$2
  [[ -f "$source" ]] || {
    echo "required firmware build header is missing: $source" >&2
    exit 69
  }
  mkdir -p -- "$(dirname -- "$target")"
  cp -a -- "$source" "$target"
}

single_build_dir() {
  local pattern=$1
  local matches=()
  shopt -s nullglob
  matches=("$output_root"/build/$pattern)
  shopt -u nullglob
  [[ ${#matches[@]} -eq 1 && -d "${matches[0]}" ]] || {
    echo "expected exactly one matching firmware build directory: build/$pattern" >&2
    exit 70
  }
  printf '%s\n' "${matches[0]}"
}

wayland_dir=$(single_build_dir 'wayland-[0-9]*')
xkb_dir=$(single_build_dir 'libxkbcommon-*')
mesa_dir=$(single_build_dir 'mesa3d-*')
pulse_dir=$(single_build_dir 'pulseaudio-*')
alsa_dir=$(single_build_dir 'alsa-lib-*')
freetype_dir=$(single_build_dir 'freetype-*')
harfbuzz_dir=$(single_build_dir 'harfbuzz-*')
zlib_dir=$(single_build_dir 'libzlib-*')

mkdir -p -- "$destination/include" "$destination/usr"
ln -s -- "$sysroot/usr/lib" "$destination/lib"
ln -s -- "$destination/lib" "$destination/usr/lib"

# Public headers from exactly the target packages selected by the matching
# image.  Wayland's public protocol headers are all in src/, while SDL_ttf
# additionally needs the normal FreeType, HarfBuzz and zlib interfaces.
find "$wayland_dir/src" -maxdepth 1 -type f -name '*.h' -exec cp -a -- {} "$destination/include/" \;
copy_tree "$xkb_dir/include/xkbcommon" "$destination/include/xkbcommon"
copy_tree "$mesa_dir/include/EGL" "$destination/include/EGL"
copy_tree "$mesa_dir/include/KHR" "$destination/include/KHR"
copy_tree "$pulse_dir/src/pulse" "$destination/include/pulse"
# ALSA's source tree represents <alsa/...> with an `alsa -> .` symlink.  Copy
# the header directory's contents below an explicit include/alsa/ directory;
# copying that symlink alone would leave asoundlib.h unresolved in the overlay.
mkdir -p -- "$destination/include/alsa"
cp -a -- "$alsa_dir/include/." "$destination/include/alsa"
copy_tree "$freetype_dir/include/freetype" "$destination/include/freetype"
copy_file "$freetype_dir/include/ft2build.h" "$destination/include/ft2build.h"
find "$harfbuzz_dir/src" -maxdepth 1 -type f -name '*.h' -exec cp -a -- {} "$destination/include/" \;
copy_file "$zlib_dir/zlib.h" "$destination/include/zlib.h"
copy_file "$zlib_dir/zconf.h" "$destination/include/zconf.h"

for required in \
  include/wayland-client.h \
  include/xkbcommon/xkbcommon.h \
  include/EGL/egl.h \
  include/pulse/pulseaudio.h \
  include/alsa/asoundlib.h \
  include/freetype/freetype.h \
  include/zlib.h \
  lib/pkgconfig/wayland-client.pc \
  lib/pkgconfig/xkbcommon.pc \
  lib/pkgconfig/libpulse.pc \
  lib/libffi.so lib/libpulse.so lib/libasound.so; do
  [[ -e "$destination/$required" ]] || {
    echo "generated SDK overlay is incomplete: $required" >&2
    exit 71
  }
done

printf 'K230 SDK development overlay ready: %s\n' "$destination"
